version: "3.0"
services:
  web:
    image: web-app
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - redis
  redis:
    image: "redis:alpine"
  mysql:
    image: "mysql:5.7"