import numpy as np
arr=np.array([1,2,3,4,5])
mean=np.mean(arr)
median=np.median(arr)
standard_deviation=np.std(arr)
print("Mean:", mean)
print("Median:", median)
print("Standard Deviation:", standard_deviation)
normalized_data=(arr - mean)/np.std(arr)
print("Normalized Data:", normalized_data)